'use strict';
/**
 * CanvasElement — stores every drawing element as an independent document.
 *
 * Separating elements from the Canvas metadata document lets us:
 *   1. Scale to truly infinite canvases (no 16 MB MongoDB doc limit).
 *   2. Perform targeted updates/deletes without re-writing the entire canvas.
 *   3. Efficiently query elements by canvasId with proper indexes.
 *   4. Soft-delete elements so undo can recover them.
 *
 * Supported element types (type field):
 *   stroke    — freehand path (pen, pencil, marker, brush, eraser)
 *   shape     — geometric shapes (rectangle, ellipse, triangle, line, arrow,
 *               diamond, parallelogram, cylinder, hexagon, star, polygon)
 *   text      — standalone text box
 *   image     — raster image (URL or small base64)
 *   frame     — grouping rectangle with title
 *   connector — smart line connecting two shapes
 *   sticky    — sticky note (colored background + text)
 */

const mongoose = require('mongoose');

// ── Sub-schemas ───────────────────────────────────────────────────────────────
const PointSchema = new mongoose.Schema(
  {
    x: { type: Number, required: true },
    y: { type: Number, required: true },
    p: { type: Number, default: 0.5 }, // stylus pressure 0–1
  },
  { _id: false }
);

// ── Main schema ───────────────────────────────────────────────────────────────
const CanvasElementSchema = new mongoose.Schema(
  {
    // ── Identity ───────────────────────────────────────────────────────────────
    canvasId:  { type: mongoose.Schema.Types.ObjectId, ref: 'Canvas', required: true },
    elementId: { type: String, required: true }, // UUID generated by the client

    // ── Classification ─────────────────────────────────────────────────────────
    type: {
      type: String,
      required: true,
      enum: ['stroke', 'shape', 'text', 'image', 'frame', 'connector', 'sticky'],
    },
    // subtype examples:
    //   stroke    → 'pen' | 'pencil' | 'marker' | 'brush' | 'eraser' | 'highlighter'
    //   shape     → 'rectangle' | 'ellipse' | 'triangle' | 'line' | 'arrow' |
    //               'diamond' | 'parallelogram' | 'cylinder' | 'hexagon' | 'star' | 'polygon'
    //   connector → 'straight' | 'curved' | 'elbow'
    subtype: { type: String },

    // ── Bounding box (canvas coordinate space, origin top-left) ────────────────
    x:        { type: Number, default: 0 },  // top-left corner x
    y:        { type: Number, default: 0 },  // top-left corner y
    width:    { type: Number, default: 0 },
    height:   { type: Number, default: 0 },
    rotation: { type: Number, default: 0 }, // degrees, clockwise

    // ── Stroke path ────────────────────────────────────────────────────────────
    points: [PointSchema], // ordered freehand path points

    // ── Connector endpoints ────────────────────────────────────────────────────
    fromElementId: { type: String },           // elementId of source shape
    toElementId:   { type: String },           // elementId of target shape
    fromPoint:     { type: PointSchema },      // absolute canvas point (override)
    toPoint:       { type: PointSchema },      // absolute canvas point (override)
    controlPoints: [PointSchema],              // Bézier midpoints for curved connectors

    // ── Text / Label ───────────────────────────────────────────────────────────
    text:       { type: String },
    label:      { type: String },              // text overlaid inside a shape
    fontSize:   { type: Number, default: 16 },
    fontFamily: { type: String, default: 'Inter, sans-serif' },
    fontWeight: { type: String, default: 'normal' },
    fontStyle:  { type: String, default: 'normal' },
    textAlign:  { type: String, enum: ['left', 'center', 'right'], default: 'left' },
    textColor:  { type: String },
    lineHeight: { type: Number, default: 1.4 },

    // ── Shared style ───────────────────────────────────────────────────────────
    strokeColor: { type: String, default: '#1e1e2e' },
    fillColor:   { type: String },
    strokeWidth: { type: Number, default: 2 },
    opacity:     { type: Number, default: 1, min: 0, max: 1 },
    dashed:      { type: Boolean, default: false },
    dashArray:   [{ type: Number }],           // e.g. [8, 4] for dash-gap pattern
    roughness:   { type: Number, default: 0 }, // 0 = smooth, 1–2 = sketchy
    roundness:   { type: Number, default: 0 }, // corner radius (px or %)

    // ── Arrow / line ends ──────────────────────────────────────────────────────
    arrowStart:     { type: Boolean, default: false },
    arrowEnd:       { type: Boolean, default: true  },
    arrowHeadStyle: {
      type: String,
      enum: ['triangle', 'open', 'dot', 'none'],
      default: 'triangle',
    },

    // ── Image ──────────────────────────────────────────────────────────────────
    imageUrl:  { type: String }, // preferred: stored/CDN URL
    imageData: { type: String }, // base64 fallback (keep small — thumbnails only)

    // ── Z-order ────────────────────────────────────────────────────────────────
    zIndex: { type: Number, default: 0 },

    // ── State ──────────────────────────────────────────────────────────────────
    isDeleted: { type: Boolean, default: false }, // soft-delete for undo support
    isLocked:  { type: Boolean, default: false }, // editing lock (set via socket)

    // ── Audit ──────────────────────────────────────────────────────────────────
    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    updatedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },

    // Version counter — incremented on every update.
    // Clients can use this for optimistic-concurrency conflict detection.
    version: { type: Number, default: 1 },
  },
  { timestamps: true }
);

// ── Indexes ───────────────────────────────────────────────────────────────────
// Primary query: fetch all non-deleted elements for a canvas
CanvasElementSchema.index({ canvasId: 1, isDeleted: 1 });
// Unique identity per canvas (prevents duplicate elementIds)
CanvasElementSchema.index({ canvasId: 1, elementId: 1 }, { unique: true });
// Ordered rendering by z-order
CanvasElementSchema.index({ canvasId: 1, zIndex: 1 });
// Connector lookups (find connectors that reference a given shape)
CanvasElementSchema.index({ canvasId: 1, fromElementId: 1 });
CanvasElementSchema.index({ canvasId: 1, toElementId:   1 });

module.exports = mongoose.model('CanvasElement', CanvasElementSchema);
